###################################################################
#
# A list of all the geos used in the game
#
###################################################################

GEOS= \
    bgrnd03.mdl \
    bgrnd05.mdl \
    mis05.mdl \
    wep01.mdl \
    wep02.mdl \
    wep03.mdl \
    wep04.mdl \
    wep05.mdl \
    wep06.mdl \
    wep07.mdl \
    wep08.mdl \
    wep09.mdl \
    wep10.mdl \
    wep11.mdl \
    wep12.mdl \
    wep13.mdl \
    wep16.mdl \
    wep17.mdl \
    wep18.mdl \
    wep19.mdl \
    acs29.mdl \
    acs34.mdl \
    acs36.mdl \
    acs38.mdl \
    acs48.mdl \
    bom04.mdl \
    bom05.mdl \
    bom07.mdl \
    utl01.mdl \
    utl02.mdl \
    utl11.mdl \
    utl14a.mdl \
    utl17a.mdl \
    utl18a.mdl \
    utl22.mdl \
    utl23.mdl \
    utl24.mdl \
    utl25.mdl \
    utl27.mdl \
    cap01.mdl \
    cap02a.mdl \
    cap03.mdl \
    cap04.mdl \
    cap06a.mdl \
    cap07.mdl \
    cap08.mdl \
    cap09.mdl \
    ops1.mdl \
    acs06.mdl \
    acs07.mdl \
    acs08.mdl \
    ss01.mdl \
    ss02.mdl \
    ss04.mdl \
    ss05.mdl \
    ss08.mdl \
    ss23.mdl \
    mis12.mdl \
    acs05.mdl \
    acs19.mdl \
    bom01a.mdl \
    ss06.mdl \
    ss19a.mdl \
    ss21a.mdl \
    ss22.mdl \
    utl04.mdl \
    utl06.mdl \
    utl28a.mdl \
    fig02.mdl \
    fig03.mdl \
    fig04.mdl \
    fig05.mdl \
    fig08.mdl \
    fig12.mdl \
    ss27.mdl \
    ss28.mdl \
    cap05.mdl \
    utl19.mdl \
    globe.mdl \
    lens.mdl

###################################################################
#
# Dependancies
#
###################################################################

all: $(GEOS)

###################################################################
#
# Geos without LOD
#
###################################################################

bgrnd03.mdl: ..\256\bgrnd03.x
    makemdlnone bgrnd03  1

bgrnd05.mdl: ..\256\bgrnd05.x
    makemdlnone bgrnd05  1

mis05.mdl: ..\256\mis05.x
    makemdlnone mis05 1

wep01.mdl: ..\256\wep01.x
    makemdlnone wep01 1

wep02.mdl: ..\256\wep02.x
    makemdlnone wep02 1

wep03.mdl: ..\256\wep03.x
    makemdlnone wep03 1

wep04.mdl: ..\256\wep04.x
    makemdlnone wep04 1

wep05.mdl: ..\256\wep05.x
    makemdlnone wep05 1

wep06.mdl: ..\256\wep06.x
    makemdlnone wep06 1

wep07.mdl: ..\256\wep07.x
    makemdlnone wep07 1

wep08.mdl: ..\256\wep08.x
    makemdlnone wep08 1

wep09.mdl: ..\256\wep09.x
    makemdlnone wep09 1

wep10.mdl: ..\256\wep10.x
    makemdlnone wep10 1

wep11.mdl: ..\256\wep11.x
    makemdlnone wep11 1

wep12.mdl: ..\256\wep12.x
    makemdlnone wep12 1

wep13.mdl: ..\256\wep13.x
    makemdlnone wep13 1

wep16.mdl: ..\256\wep16.x
    makemdlnone wep16 1

wep17.mdl: ..\256\wep17.x
    makemdlnone wep17 1

wep18.mdl: ..\256\wep18.x
    makemdlnone wep18 1

wep19.mdl: ..\256\wep19.x
    makemdlnone wep19 1

acs29.mdl: ..\256\acs29.x
    makemdlnone acs29 1

acs34.mdl: ..\256\acs34.x
    makemdlnone acs34 1

acs36.mdl: ..\256\acs36.x
    makemdlnone acs36 1

acs38.mdl: ..\256\acs38.x
    makemdlnone acs38 1

acs48.mdl: ..\256\acs48.x
    makemdlnone acs48 1

bom04.mdl: ..\256\bom04.x
    makemdlnone bom04 1

bom05.mdl: ..\256\bom05.x
    makemdlnone bom05 1

bom07.mdl: ..\256\bom07.x
    makemdlnone bom07 1

utl01.mdl: ..\256\utl01.x
    makemdlnone utl01 1

utl02.mdl: ..\256\utl02.x
    makemdlnone utl02 1

utl11.mdl: ..\256\utl11.x
    makemdlnone utl11 1

utl14a.mdl: ..\256\utl14a.x
    makemdlnone utl14a 1

utl17a.mdl: ..\256\utl17a.x
    makemdlnone utl17a 1

utl18a.mdl: ..\256\utl18a.x
    makemdlnone utl18a 1

utl22.mdl: ..\256\utl22.x
    makemdlnone utl22 1

utl23.mdl: ..\256\utl23.x
    makemdlnone utl23 1

utl24.mdl: ..\256\utl24.x
    makemdlnone utl24 1

utl25.mdl: ..\256\utl25.x
    makemdlnone utl25 1

utl27.mdl: ..\256\utl27.x
    makemdlnone utl27 1

cap01.mdl: ..\256\cap01.x
    makemdlnone cap01 1

cap02a.mdl: ..\256\cap02a.x
    makemdlnone cap02a 1

cap03.mdl: ..\256\cap03.x
    makemdlnone cap03 1

cap04.mdl: ..\256\cap04.x
    makemdlnone cap04 1

cap06a.mdl: ..\256\cap06a.x
    makemdlnone cap06a 1

cap07.mdl: ..\256\cap07.x
    makemdlnone cap07 1

cap08.mdl: ..\256\cap08.x
    makemdlnone cap08 1

cap09.mdl: ..\256\cap09.x
    makemdlnone cap09 1

ops1.mdl: ..\256\ops1.x
    makemdlnone ops1 1

acs06.mdl: ..\256\acs06.x
    makemdlnone acs06 1

acs07.mdl: ..\256\acs07.x
    makemdlnone acs07 1

acs08.mdl: ..\256\acs08.x
    makemdlnone acs08 1

ss01.mdl: ..\256\ss01.x
    makemdlnone ss01 1

ss02.mdl: ..\256\ss02.x
    makemdlnone ss02 1

ss04.mdl: ..\256\ss04.x
    makemdlnone ss04 1

ss05.mdl: ..\256\ss05.x
    makemdlnone ss05 1

ss08.mdl: ..\256\ss08.x
    makemdlnone ss08 1

ss23.mdl: ..\256\ss23.x
    makemdlnone ss23 1

fig08.mdl: ..\256\fig08.x
    makemdlnone fig08 16

###################################################################
#
# Geos with LOD
#
###################################################################

mis12.mdl: ..\256\mis12.x
    makemdl mis12 template 1

acs05.mdl: ..\256\acs05.x
    makemdl acs05 template 1

acs19.mdl: ..\256\acs19.x
    makemdl acs19 template 1

bom01a.mdl: ..\256\bom01a.x
    makemdl bom01a template 16

ss06.mdl: ..\256\ss06.x
    makemdl ss06 template 1

ss19a.mdl: ..\256\ss19a.x
    makemdl ss19a template 1

ss21a.mdl: ..\256\ss21a.x
    makemdl ss21a template 1

ss22.mdl: ..\256\ss22.x
    makemdl ss22 template 1

utl04.mdl: ..\256\utl04.x
    makemdl utl04 template 1

utl06.mdl: ..\256\utl06.x
    makemdl utl06 template 1

utl28a.mdl: ..\256\utl28a.x
    makemdl utl28a template 1

fig02.mdl: ..\256\fig02.x
    makemdl fig02 templatelow 16

fig03.mdl: ..\256\fig03.x
    makemdl fig03 templatelow 16

fig04.mdl: ..\256\fig04.x
    makemdl fig04 templatelow 16

fig05.mdl: ..\256\fig05.x
    makemdl fig05 templatelow 16

fig12.mdl: ..\256\fig12.x
    makemdl fig12 templatelow 16

ss27.mdl: ..\256\ss27.x
    makemdl ss27 templatelow 1

ss28.mdl: ..\256\ss28.x
    makemdl ss28 templatelow 1

cap05.mdl: ..\256\cap05.x
    makemdl cap05 templatelow 1

utl19.mdl: ..\256\utl19.x
    makemdl utl19 templatelow 1

###################################################################
#
# Other Geos
#
###################################################################

globe.mdl: ..\256\globe.x globetext.mdl
    copy ..\256\globe.x
    $(FEDROOT)\objs\debug\mdlc\mdlc -optimize globetext globe
    erase globe.x

lens.mdl: ..\256\lens30.x ..\256\lens60.x ..\256\lens90.x lenstext.mdl
    copy ..\256\lens30.x
    copy ..\256\lens60.x
    copy ..\256\lens90.x
    $(FEDROOT)\objs\debug\mdlc\mdlc lenstext lens
    erase lens30.x
    erase lens60.x
    erase lens90.x
